# Makefile.bresenhan — versão para MSVC/nmake

CC     = cl
CFLAGS = /Ox /W3

SDL_INC = /I"E:\vcpkg\installed\x64-windows\include"
SDL_LIB = "E:\vcpkg\installed\x64-windows\lib\SDL3.lib"

all: bresenhan.exe

bresenhan.exe: bresenhan.c
	$(CC) $(CFLAGS) /Fe:bresenhan.exe bresenhan.c $(SDL_INC) $(SDL_LIB)

clean:
	-del /q *.obj *.exe 2>nul