/*
 * spiral.c — emergent spiral CA on pulsating wavefront
 *
 * The spiral is a cylindrical helix generated by a walker:
 *   - Walker starts at grid center (MID, MID, MID)
 *   - Advances 1 cell per tick along a cylinder of radius R_CYL
 *   - Bresenham accumulator interleaves planar (rotation) and
 *     vertical (climb) steps
 *   - Planar direction chosen by minimizing |dist²_cyl - R_CYL²|
 *     with CCW preference via tangent dot product
 *
 * Runtime CA operations: addition, subtraction, shift, comparison.
 * No multiplication, no division, no lookup tables, no floats.
 * (pulse_from_time and rendering use multiplication — host-only)
 */

#include "spiral.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* --- Grid allocation (heap, too large for stack) --- */
Cell (*grid)[L][L]      = NULL;
Cell (*grid_next)[L][L] = NULL;

int tick = 0;

/* --- Spiral walker state --- */
SpiralPt spiral_pts[MAX_SPIRAL_PTS];
int spiral_n    = 0;
int spiral_done = 0;

static int tip_x, tip_y, tip_z;   /* current walker position */
static int tip_dx, tip_dy;        /* displacement from cylinder axis */
static int tip_d2;                /* distance² to cylinder axis */
static int tip_acc;               /* Bresenham accumulator for pitch */

/* ==========================================================
 * Initialization
 * ========================================================== */
void init(void) {
    for (int x = 0; x < L; x++)
    for (int y = 0; y < L; y++)
    for (int z = 0; z < L; z++) {
        Cell *c  = &grid[x][y][z];
        c->r     = 0;
        c->r2    = INF_R2;
        c->active = 0;
        c->spin  = 0;

        Cell *cn  = &grid_next[x][y][z];
        cn->r     = 0;
        cn->r2    = INF_R2;
        cn->active = 0;
        cn->spin  = 0;
    }

    /* seed center */
    grid[MID][MID][MID].r2 = 0;
    grid[MID][MID][MID].r  = 0;

    /* init walker */
    spiral_init();
}

/* ==========================================================
 * spiral_init — seed the cylindrical-helix walker at center
 *
 * Starting point (MID,MID,MID) is exactly on the cylinder
 * surface: distance from axis (CYL_X0, CYL_Y0) = R_CYL.
 * ========================================================== */
void spiral_init(void) {
    tip_x  = MID;
    tip_y  = MID;
    tip_z  = MID;
    tip_dx = MID - CYL_X0;          /* = 0 */
    tip_dy = MID - CYL_Y0;          /* = -R_CYL */
    tip_d2 = tip_dx * tip_dx        /* init-time multiplication OK */
           + tip_dy * tip_dy;        /* = R_CYL_SQ */
    tip_acc = 0;
    spiral_done = 0;
    spiral_n = 0;

    /* mark starting cell */
    grid[MID][MID][MID].spin = 1;
    spiral_pts[0].x = MID;
    spiral_pts[0].y = MID;
    spiral_pts[0].z = MID;
    spiral_n = 1;
}

/* ==========================================================
 * BFS wavefront propagation (sum-of-odds for r2)
 *
 * Pure distance propagation — no spiral state in cells.
 * ========================================================== */
static const int ddx[6] = {1, -1, 0,  0, 0,  0};
static const int ddy[6] = {0,  0, 1, -1, 0,  0};
static const int ddz[6] = {0,  0, 0,  0, 1, -1};

static void pulse_update_wavefront(void) {
    /* snapshot current r2 into grid_next */
    for (int x = 0; x < L; x++)
    for (int y = 0; y < L; y++)
    for (int z = 0; z < L; z++) {
        grid_next[x][y][z].r2 = grid[x][y][z].r2;
    }

    for (int x = 0; x < L; x++)
    for (int y = 0; y < L; y++)
    for (int z = 0; z < L; z++) {
        if (grid[x][y][z].r2 == INF_R2) continue;

        unsigned int ax = (x > MID) ? (unsigned int)(x - MID)
                                     : (unsigned int)(MID - x);
        unsigned int ay = (y > MID) ? (unsigned int)(y - MID)
                                     : (unsigned int)(MID - y);
        unsigned int az = (z > MID) ? (unsigned int)(z - MID)
                                     : (unsigned int)(MID - z);

        for (int d = 0; d < 6; d++) {
            int nx = x + ddx[d];
            int ny = y + ddy[d];
            int nz = z + ddz[d];
            if (nx < 0 || nx >= L || ny < 0 || ny >= L ||
                nz < 0 || nz >= L)
                continue;

            /* sum-of-odds distance update */
            unsigned int diff;
            if (d < 2)      diff = (ax << 1) + 1;
            else if (d < 4) diff = (ay << 1) + 1;
            else            diff = (az << 1) + 1;

            unsigned int new_r2 = grid[x][y][z].r2 + diff;
            if (new_r2 < grid_next[nx][ny][nz].r2) {
                grid_next[nx][ny][nz].r2 = new_r2;
            }
        }
    }
}

/* ==========================================================
 * pulse_step — BFS + copy-back + activation flags
 * ========================================================== */
void pulse_step(void) {
    pulse_update_wavefront();
    grid_next[MID][MID][MID].r2 = 0;

    /* copy back r2; compute r for newly visited */
    for (int x = 0; x < L; x++)
    for (int y = 0; y < L; y++)
    for (int z = 0; z < L; z++) {
        unsigned int old_r2 = grid[x][y][z].r2;
        unsigned int new_r2 = grid_next[x][y][z].r2;
        grid[x][y][z].r2 = new_r2;
        if (new_r2 != INF_R2 && old_r2 == INF_R2) {
            grid[x][y][z].r = isqrt((int)new_r2);
        }
    }

    /* activation flags (pulsating shell) */
    unsigned int pulse_r2 = pulse_from_time((unsigned int)tick);
    for (int x = 0; x < L; x++)
    for (int y = 0; y < L; y++)
    for (int z = 0; z < L; z++) {
        unsigned int r2 = grid[x][y][z].r2;
        if (r2 == INF_R2) {
            grid[x][y][z].active = 0;
        } else {
            unsigned int delta = (r2 > pulse_r2)
                               ? (r2 - pulse_r2)
                               : (pulse_r2 - r2);
            grid[x][y][z].active = (delta <= PULSE_TOLERANCE) ? 1 : 0;
        }
    }
}

/* ==========================================================
 * spiral_step — advance the cylindrical-helix walker by 1 cell
 *
 * Each tick: Bresenham decides planar vs z-step.
 *   z-step:     tip_z++
 *   planar step: evaluate 4 neighbours,
 *                pick min |dist²_cyl - R_CYL²|
 *                break ties by CCW tangent dot product
 *
 * Incremental dist² update (sum-of-odds):
 *   move +x: dist² += (dx_cyl << 1) + 1       (then dx_cyl++)
 *   move -x: dist² -= (dx_cyl << 1) - 1       (then dx_cyl--)
 *   move +y: dist² += (dy_cyl << 1) + 1       (then dy_cyl++)
 *   move -y: dist² -= (dy_cyl << 1) - 1       (then dy_cyl--)
 *   move ±z: dist² unchanged (axis parallel to z)
 *
 * No multiplication, no division, no loops.
 * ========================================================== */
void spiral_step(void) {
    if (spiral_done) return;

    /* --- Bresenham: decide planar vs z-step ---
     * Distribute R_MAX z-steps among CYL_CIRC planar steps.
     * Total = CYL_TOTAL = CYL_CIRC + R_MAX.
     * Each tick: acc += R_MAX.
     * If acc >= CYL_TOTAL → this tick is a z-step (acc -= CYL_TOTAL).
     * Otherwise → planar step. */
    int new_acc = tip_acc + R_MAX;
    int do_z;
    if (new_acc >= CYL_TOTAL) {
        new_acc -= CYL_TOTAL;
        do_z = 1;
    } else {
        do_z = 0;
    }
    tip_acc = new_acc;

    if (do_z) {
        /* ---- z-step ---- */
        tip_z++;
        if (tip_z >= L) { spiral_done = 1; return; }
    } else {
        /* ---- planar step: choose best direction on cylinder ---- */

        /* Candidate dist² for each direction (sum-of-odds) */
        int d2_px = tip_d2 + (tip_dx << 1) + 1;   /* +x */
        int d2_mx = tip_d2 - (tip_dx << 1) + 1;   /* -x */
        int d2_py = tip_d2 + (tip_dy << 1) + 1;   /* +y */
        int d2_my = tip_d2 - (tip_dy << 1) + 1;   /* -y */

        /* Radial error: |dist² - R_CYL²| */
        int e_px = d2_px > R_CYL_SQ ? d2_px - R_CYL_SQ : R_CYL_SQ - d2_px;
        int e_mx = d2_mx > R_CYL_SQ ? d2_mx - R_CYL_SQ : R_CYL_SQ - d2_mx;
        int e_py = d2_py > R_CYL_SQ ? d2_py - R_CYL_SQ : R_CYL_SQ - d2_py;
        int e_my = d2_my > R_CYL_SQ ? d2_my - R_CYL_SQ : R_CYL_SQ - d2_my;

        /* Validity: in bounds AND not already spin */
        int v_px = (tip_x + 1 < L)  && !grid[tip_x + 1][tip_y][tip_z].spin;
        int v_mx = (tip_x - 1 >= 0) && !grid[tip_x - 1][tip_y][tip_z].spin;
        int v_py = (tip_y + 1 < L)  && !grid[tip_x][tip_y + 1][tip_z].spin;
        int v_my = (tip_y - 1 >= 0) && !grid[tip_x][tip_y - 1][tip_z].spin;

        /* CCW tangent = (-dy_cyl, +dx_cyl).
         * Dot product of each direction with tangent (no multiplication): */
        int t_px = -tip_dy;    /* (+1,0) · (-dy, dx) = -dy */
        int t_mx =  tip_dy;    /* (-1,0) · (-dy, dx) =  dy */
        int t_py =  tip_dx;    /* (0,+1) · (-dy, dx) =  dx */
        int t_my = -tip_dx;    /* (0,-1) · (-dy, dx) = -dx */

        /* Find best: minimum error among CCW directions only
         * (positive tangent dot product prevents backward moves
         *  across z-levels where visited mask resets) */
        int best = -1;
        int best_err = 0x7FFFFFFF;

        /* +x (CCW only) */
        if (v_px && t_px > 0 && e_px < best_err) {
            best = 0; best_err = e_px;
        }
        /* -x (CCW only) */
        if (v_mx && t_mx > 0 && e_mx < best_err) {
            best = 1; best_err = e_mx;
        }
        /* +y (CCW only) */
        if (v_py && t_py > 0 && e_py < best_err) {
            best = 2; best_err = e_py;
        }
        /* -y (CCW only) */
        if (v_my && t_my > 0 && e_my < best_err) {
            best = 3; best_err = e_my;
        }

        /* Fallback: any valid direction if no CCW direction found */
        if (best < 0) {
            if (v_px && e_px < best_err) { best = 0; best_err = e_px; }
            if (v_mx && e_mx < best_err) { best = 1; best_err = e_mx; }
            if (v_py && e_py < best_err) { best = 2; best_err = e_py; }
            if (v_my && e_my < best_err) { best = 3; best_err = e_my; }
        }

        if (best < 0) {
            /* no valid planar direction — force z-step as fallback */
            tip_z++;
            if (tip_z >= L) { spiral_done = 1; return; }
        } else {
            switch (best) {
            case 0: /* +x: dist² += 2·dx + 1, then dx++ */
                tip_d2 += (tip_dx << 1) + 1;
                tip_dx++;
                tip_x++;
                break;
            case 1: /* -x: dist² -= 2·dx - 1, then dx-- */
                tip_d2 -= (tip_dx << 1) - 1;
                tip_dx--;
                tip_x--;
                break;
            case 2: /* +y: dist² += 2·dy + 1, then dy++ */
                tip_d2 += (tip_dy << 1) + 1;
                tip_dy++;
                tip_y++;
                break;
            case 3: /* -y: dist² -= 2·dy - 1, then dy-- */
                tip_d2 -= (tip_dy << 1) - 1;
                tip_dy--;
                tip_y--;
                break;
            }
        }
    }

    /* mark the new cell */
    if (tip_x >= 0 && tip_x < L &&
        tip_y >= 0 && tip_y < L &&
        tip_z >= 0 && tip_z < L) {
        grid[tip_x][tip_y][tip_z].spin = 1;
        if (spiral_n < MAX_SPIRAL_PTS) {
            spiral_pts[spiral_n].x = tip_x;
            spiral_pts[spiral_n].y = tip_y;
            spiral_pts[spiral_n].z = tip_z;
            spiral_n++;
        }
    }

    /* done when we reach the pole */
    if (tip_z >= MID + R_MAX) spiral_done = 1;
}

/* ==========================================================
 * Unified step — pulsating wavefront, then spiral advance
 * ========================================================== */
void step_all(void) {
    pulse_step();
    spiral_step();
    tick++;
}

/* ==========================================================
 * Rendering (SDL3)
 * ========================================================== */
#ifndef NO_SDL

void render_frame(SDL_Renderer *ren) {
    SDL_SetRenderDrawColor(ren, 0, 0, 0, 255);
    SDL_RenderClear(ren);

    unsigned int pulse_r2 = pulse_from_time((unsigned int)tick);
    int cur_r = isqrt((int)pulse_r2);

    /* -------------------------------------------------------
     * Panel 1 (top-left): wavefront z=MID slice
     *   green = distance gradient, yellow = active shell
     * ------------------------------------------------------- */
    {
        int ox = 30;
        for (int x = 0; x < L; x++)
        for (int y = 0; y < L; y++) {
            Cell *c = &grid[x][y][MID];
            unsigned int pr = 0, pg = 0, pb = 0;

            if (c->r2 != INF_R2) {
                int rr = isqrt((int)c->r2);
                int g = (rr < RADIUS) ? 255 - (rr * 255 / RADIUS) : 0;
                pg = (unsigned int)g;
            }

            {
                int delta = (int)c->r2 - (int)pulse_r2;
                if (delta < 0) delta = -delta;
                if (delta <= YELLOW_VIS_TOL) {
                    pr = 255; pg = 255; pb = 0;
                }
            }

            SDL_SetRenderDrawColor(ren,
                (Uint8)pr, (Uint8)pg, (Uint8)pb, 255);
            SDL_RenderPoint(ren, (float)(x + ox), (float)(y + 10));
        }
    }

    /* -------------------------------------------------------
     * Panel 2 (top-right, large): 3D isometric view of spiral
     *   Uses stored spiral_pts[] — no Bresenham re-trace.
     *   cyan = spin, white = spin+active.
     * ------------------------------------------------------- */
    {
        int panel_x = 30 + L + 40;
        int panel_y = 10;
        int panel_w = 480;
        int panel_h = L;
        float cx = (float)(panel_x + panel_w / 2);
        float cy = (float)(panel_y + panel_h / 2);
        float scale = (float)panel_h / (3.2f * (float)R_MAX);

        float ax = 0.866f;   /* cos(30°) */
        float ay = 0.5f;     /* sin(30°) */
        float ez = 1.0f;

        /* Render spiral points */
        for (int i = 0; i < spiral_n; i++) {
            int sx = spiral_pts[i].x;
            int sy = spiral_pts[i].y;
            int sz = spiral_pts[i].z;
            int ldx = sx - MID;
            int ldy = sy - MID;
            int dz  = sz - MID;

            float px = cx + ((float)ldx - (float)ldy) * ax * scale;
            float py = cy - (float)dz * ez * scale
                     + ((float)ldx + (float)ldy) * ay * scale;

            if (grid[sx][sy][sz].active) {
                SDL_SetRenderDrawColor(ren, 255, 255, 255, 255);
            } else {
                int bright = 150 + (ldx + ldy) / 4;
                if (bright > 255) bright = 255;
                if (bright < 80) bright = 80;
                SDL_SetRenderDrawColor(ren,
                    0, (Uint8)bright, (Uint8)bright, 255);
            }
            SDL_FRect rc = { px - 1, py - 1, 3, 3 };
            SDL_RenderFillRect(ren, &rc);
        }

        /* --- Coordinate axes (RGB = XYZ) --- */
        {
            float axis_len = (float)RADIUS * scale;

            /* X axis (red) */
            float x_end_px = cx + axis_len * ax;
            float x_end_py = cy + axis_len * ay;
            SDL_SetRenderDrawColor(ren, 180, 50, 50, 255);
            SDL_RenderLine(ren, cx, cy, x_end_px, x_end_py);

            /* Y axis (green) */
            float y_end_px = cx - axis_len * ax;
            float y_end_py = cy + axis_len * ay;
            SDL_SetRenderDrawColor(ren, 50, 180, 50, 255);
            SDL_RenderLine(ren, cx, cy, y_end_px, y_end_py);

            /* Z axis (blue up, dark blue down) */
            float z_end_py = cy - (float)R_MAX * ez * scale;
            SDL_SetRenderDrawColor(ren, 80, 80, 255, 255);
            SDL_RenderLine(ren, cx, cy, cx, z_end_py);
            float z_neg_py = cy + (float)R_MAX * ez * scale;
            SDL_SetRenderDrawColor(ren, 40, 40, 120, 255);
            SDL_RenderLine(ren, cx, cy, cx, z_neg_py);
        }

        /* --- Cosmetic sphere silhouette --- */
        {
            int n_seg = 64;
            float sil_r = (float)RADIUS * scale;
            float prev_px2 = 0.0f, prev_py2 = 0.0f;

            SDL_SetRenderDrawColor(ren, 35, 35, 35, 255);
            for (int i = 0; i <= n_seg; i++) {
                float angle = (float)i * 6.2832f / (float)n_seg;
                float ppx = cx + sil_r * cosf(angle);
                float ppy = cy + sil_r * sinf(angle);
                if (i > 0)
                    SDL_RenderLine(ren, prev_px2, prev_py2, ppx, ppy);
                prev_px2 = ppx;
                prev_py2 = ppy;
            }
        }
    }

    /* -------------------------------------------------------
     * Panels 3-5: Orthographic projections (XY, XZ, YZ)
     * ------------------------------------------------------- */
    {
        int tp_sz = 155;
        int tp_base_x = 30 + L + 40;
        int tp_base_y = L + 30;
        float tp_scale = (float)tp_sz / (2.2f * (float)RADIUS);

        int panel_idx;
        for (panel_idx = 0; panel_idx < 3; panel_idx++) {
            int tp_x = tp_base_x + panel_idx * (tp_sz + 5);
            float tp_cx = (float)tp_x + (float)tp_sz * 0.5f;
            float tp_cy = (float)tp_base_y + (float)tp_sz * 0.5f;

            /* Outer boundary circle */
            {
                int n_seg = 48;
                float prev_px2 = 0.0f, prev_py2 = 0.0f;
                SDL_SetRenderDrawColor(ren, 35, 35, 35, 255);
                for (int i = 0; i <= n_seg; i++) {
                    float angle = (float)i * 6.2832f / (float)n_seg;
                    float px2 = tp_cx + (float)RADIUS * cosf(angle) * tp_scale;
                    float py2 = tp_cy + (float)RADIUS * sinf(angle) * tp_scale;
                    if (i > 0)
                        SDL_RenderLine(ren, prev_px2, prev_py2, px2, py2);
                    prev_px2 = px2;
                    prev_py2 = py2;
                }
            }

            /* Wavefront circle (current radius) */
            {
                int n_seg = 48;
                float prev_px2 = 0.0f, prev_py2 = 0.0f;
                SDL_SetRenderDrawColor(ren, 50, 50, 0, 255);
                for (int i = 0; i <= n_seg; i++) {
                    float angle = (float)i * 6.2832f / (float)n_seg;
                    float px2 = tp_cx + (float)cur_r * cosf(angle) * tp_scale;
                    float py2 = tp_cy + (float)cur_r * sinf(angle) * tp_scale;
                    if (i > 0)
                        SDL_RenderLine(ren, prev_px2, prev_py2, px2, py2);
                    prev_px2 = px2;
                    prev_py2 = py2;
                }
            }

            /* Axes */
            {
                float axis_len = (float)RADIUS * tp_scale;
                if (panel_idx == 0) {
                    SDL_SetRenderDrawColor(ren, 140, 40, 40, 255);
                    SDL_RenderLine(ren, tp_cx, tp_cy, tp_cx + axis_len, tp_cy);
                    SDL_SetRenderDrawColor(ren, 40, 140, 40, 255);
                    SDL_RenderLine(ren, tp_cx, tp_cy, tp_cx, tp_cy + axis_len);
                } else if (panel_idx == 1) {
                    SDL_SetRenderDrawColor(ren, 140, 40, 40, 255);
                    SDL_RenderLine(ren, tp_cx, tp_cy, tp_cx + axis_len, tp_cy);
                    SDL_SetRenderDrawColor(ren, 40, 40, 180, 255);
                    SDL_RenderLine(ren, tp_cx, tp_cy, tp_cx, tp_cy - axis_len);
                } else {
                    SDL_SetRenderDrawColor(ren, 40, 140, 40, 255);
                    SDL_RenderLine(ren, tp_cx, tp_cy, tp_cx + axis_len, tp_cy);
                    SDL_SetRenderDrawColor(ren, 40, 40, 180, 255);
                    SDL_RenderLine(ren, tp_cx, tp_cy, tp_cx, tp_cy - axis_len);
                }
            }

            /* Spiral points from stored array */
            for (int i = 0; i < spiral_n; i++) {
                int spx = spiral_pts[i].x - MID;
                int spy = spiral_pts[i].y - MID;
                int spz = spiral_pts[i].z - MID;
                float scr_x, scr_y;

                if (panel_idx == 0) {
                    scr_x = tp_cx + (float)spx * tp_scale;
                    scr_y = tp_cy + (float)spy * tp_scale;
                } else if (panel_idx == 1) {
                    scr_x = tp_cx + (float)spx * tp_scale;
                    scr_y = tp_cy - (float)spz * tp_scale;
                } else {
                    scr_x = tp_cx + (float)spy * tp_scale;
                    scr_y = tp_cy - (float)spz * tp_scale;
                }

                if (grid[spiral_pts[i].x][spiral_pts[i].y][spiral_pts[i].z].active) {
                    SDL_SetRenderDrawColor(ren, 255, 255, 255, 255);
                    SDL_FRect rc = { scr_x - 2, scr_y - 2, 5, 5 };
                    SDL_RenderFillRect(ren, &rc);
                } else {
                    SDL_SetRenderDrawColor(ren, 0, 200, 200, 255);
                    SDL_FRect rc = { scr_x - 1, scr_y - 1, 3, 3 };
                    SDL_RenderFillRect(ren, &rc);
                }
            }
        }
    }

    /* -------------------------------------------------------
     * Bottom graph: spiral XY trajectory vs z
     *   red = (x - MID), green = (y - MID) for each spiral point
     * ------------------------------------------------------- */
    {
        int gx0 = 30;
        int gy0 = L + 50;
        int gw  = L;
        int gh  = 180;

        /* axis */
        SDL_SetRenderDrawColor(ren, 80, 80, 80, 255);
        SDL_RenderLine(ren, (float)gx0, (float)(gy0 + gh),
                       (float)(gx0 + gw), (float)(gy0 + gh));
        SDL_RenderLine(ren, (float)gx0, (float)gy0,
                       (float)gx0, (float)(gy0 + gh));
        /* zero line */
        SDL_SetRenderDrawColor(ren, 40, 40, 40, 255);
        SDL_RenderLine(ren, (float)gx0, (float)(gy0 + gh / 2),
                       (float)(gx0 + gw), (float)(gy0 + gh / 2));

        /* plot spiral points: x-displacement (red), y-displacement (green) */
        for (int i = 0; i < spiral_n; i++) {
            int z_idx = spiral_pts[i].z;
            int sx_off = spiral_pts[i].x - MID;
            int sy_off = spiral_pts[i].y - MID;

            int px = gx0 + z_idx;
            if (px < gx0 || px > gx0 + gw) continue;

            /* x displacement (red) */
            int py_x = gy0 + gh / 2 - (sx_off * gh / (R_MAX + R_MAX + 1));
            if (py_x < gy0) py_x = gy0;
            if (py_x > gy0 + gh) py_x = gy0 + gh;
            SDL_SetRenderDrawColor(ren, 255, 80, 80, 255);
            SDL_RenderPoint(ren, (float)px, (float)py_x);

            /* y displacement (green) */
            int py_y = gy0 + gh / 2 - (sy_off * gh / (R_MAX + R_MAX + 1));
            if (py_y < gy0) py_y = gy0;
            if (py_y > gy0 + gh) py_y = gy0 + gh;
            SDL_SetRenderDrawColor(ren, 80, 255, 80, 255);
            SDL_RenderPoint(ren, (float)px, (float)py_y);
        }

        /* vertical marker at current sweep z-levels */
        if (cur_r < R_MAX) {
            SDL_SetRenderDrawColor(ren, 60, 60, 60, 255);
            int z1 = MID + cur_r;
            int z2 = MID - cur_r;
            if (z1 < L) {
                SDL_RenderLine(ren,
                    (float)(gx0 + z1), (float)gy0,
                    (float)(gx0 + z1), (float)(gy0 + gh));
            }
            if (z2 >= 0) {
                SDL_RenderLine(ren,
                    (float)(gx0 + z2), (float)gy0,
                    (float)(gx0 + z2), (float)(gy0 + gh));
            }
        }
    }

    /* status line */
    {
        int spin_count = 0;
        for (int x = 0; x < L; x++)
        for (int y = 0; y < L; y++) {
            if (grid[x][y][MID].spin) spin_count++;
        }
        printf("\r[tick %4d] r=%3d  spiral=%3d/%d  R_CYL=%d  CYL_CIRC=%d  ",
               tick, cur_r, spiral_n, CYL_TOTAL + 1,
               R_CYL, CYL_CIRC);
        fflush(stdout);
    }

    SDL_RenderPresent(ren);
}

#endif /* !NO_SDL */

/* ==========================================================
 * Main (requires SDL)
 * ========================================================== */
#ifndef NO_SDL
int main(void) {
    if (!SDL_Init(SDL_INIT_VIDEO)) {
        printf("SDL_Init error: %s\n", SDL_GetError());
        return 1;
    }

    SDL_Window *window = SDL_CreateWindow(
        "CA — cylindrical helix on pulsating wavefront",
        WINDOW_W, WINDOW_H, 0);
    if (!window) {
        printf("Window error: %s\n", SDL_GetError());
        SDL_Quit();
        return 1;
    }

    SDL_Renderer *renderer = SDL_CreateRenderer(window, NULL);
    if (!renderer) {
        printf("Renderer error: %s\n", SDL_GetError());
        SDL_DestroyWindow(window);
        SDL_Quit();
        return 1;
    }

    /* allocate grids on heap */
    grid      = malloc(sizeof(Cell) * L * L * L);
    grid_next = malloc(sizeof(Cell) * L * L * L);
    if (!grid || !grid_next) {
        printf("Out of memory (need ~%lu MB)\n",
               (unsigned long)(2 * sizeof(Cell) * L * L * L / (1024*1024)));
        return 1;
    }
    memset(grid,      0, sizeof(Cell) * L * L * L);
    memset(grid_next, 0, sizeof(Cell) * L * L * L);

    init();

    int running = 1;
    while (running) {
        SDL_Event e;
        while (SDL_PollEvent(&e)) {
            if (e.type == SDL_EVENT_QUIT) running = 0;
        }

        step_all();
        render_frame(renderer);
        SDL_Delay(16);
    }

    free(grid);
    free(grid_next);
    SDL_DestroyRenderer(renderer);
    SDL_DestroyWindow(window);
    SDL_Quit();
    return 0;
}
#endif /* !NO_SDL */